from youtube_transcript_api import *
from deep_translator import GoogleTranslator

ytt_api = YouTubeTranscriptApi()

def transcript(url:str) -> str:
    video_id = url.split('watch?v=')[-1]

    return ytt_api.fetch(video_id, languages=('en','hi'))

    # retrieve the available transcripts
    # transcript_list:TranscriptList = ytt_api.list(video_id)

    # # iterate over all available transcripts
    # for transcript in transcript_list:

    #     # the Transcript object provides metadata properties
    #     print(
    #         transcript.video_id,
    #         transcript.language,
    #         transcript.language_code,
    #         # whether it has been manually created or generated by YouTube
    #         transcript.is_generated,
    #         # whether this transcript can be translated or not
    #         transcript.is_translatable,
    #         # a list of languages the transcript can be translated to
    #     )
    #     print(transcript.fetch(True))
    #     # fetch the actual transcript data
    #     # print(transcript.fetch())

    #     # # translating the transcript will return another transcript object
    #     # print(transcript.translate('en').fetch())

if __name__ == "__main__":
    vid_url = input("Video Url:")
    print(transcript(vid_url))